trigger:
- main

resources:
- repo: self


variables:
   
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'fac06dfc-11e7-4bd5-af2c-26c5c1b96556'
  imageRepository: 'sniqurbestrongbackend'
  containerRegistry: 'bestrongacr123.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: 'latest'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  azureSubscription: 'backend_service_connection'
  appServiceName: 'BeStrongWebApp1'
  resourceGroupName: 'BeStrong-RG'

stages:
# Stage 1: Build and Push Docker Image to ACR
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build Docker Image and Push to ACR
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Bash@3
      displayName: "Azure Login"
      inputs:
        targetType: 'inline'
        script: |
                az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
                az account set --subscription $(ARM_SUBSCRIPTION_ID)   
    
    - task: Bash@3
      displayName: 'Docker Login to ACR'
      inputs:
        targetType: 'inline'
        script: |
            echo "Logging in to Azure Container Registry..."
            docker login $(containerRegistry) -u $(ACR_USERNAME) -p $(ACR_PASSWORD)


    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)


# Stage 2: Deploy Docker Image to Azure Web App (Manual Approval Required)
- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: ManualApproval
    displayName: Await manual approval
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: '<your-email@example.com>'
        instructions: 'Please approve to deploy the image to Azure Web App'



  - job: Deploy
    displayName: Deploy Docker Image to Azure Web App
    dependsOn: ManualApproval
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy Docker Image to Azure Web App'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1(1a8f5438-2e23-4a1f-b53c-3ebf42a36c48)'
        appType: 'webAppContainer'
        WebAppName: 'BeStrongWebApp'
        ResourceGroupName: 'BeStrong-RG'
        DockerNamespace: 'bestrongacr123.azurecr.io'
        DockerRepository: 'sniqurbestrongbackend'
        DockerImageTag: 'latest'
        StartupCommand: 'dotnet SampleWebApiAspNetCore.dll'
        
